using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Reflection;
using System.Diagnostics;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.MSBuild;

namespace LocatorGeneratorTool;

internal static class Program
{
    private static string Version
    {
        get
        {
            return Assembly.GetExecutingAssembly().GetName().Version?.ToString() ?? "";
        }
    }
    private static async Task Main(string[] args)
    {
        try
        {
            // Ensure the project path argument is provided
            if (args.Length < 3)
            {
                Console.WriteLine($"LocatorGenerator version {Version}");
                Console.WriteLine("");
                Console.WriteLine("Usage:");
                Console.WriteLine("");
                Console.WriteLine("");
                Console.WriteLine("LocatorGenerator [SolutionPath] [ProjectFile] [OutputDirectory]");
                Console.WriteLine("");
                Console.WriteLine($"You suplayed {args.Length} arguments : {string.Join(' ', args)} ");
                Console.WriteLine("");

                return;
            }
            else
            {
                Console.WriteLine($"LocatorGenerator version {Version}");
            }

            string solutionPath    = args[0];
            string projectFile     = args[1];
            string outputDirectory = args[2];

            Console.WriteLine($"Solution Path   : {solutionPath}");
            Console.WriteLine($"ProjectFile     : {projectFile}");
            Console.WriteLine($"Output Directory: {outputDirectory}");

            string projectPathFileName = Path.Combine(solutionPath, projectFile);

            using MSBuildWorkspace workspace = MSBuildWorkspace.Create();

            workspace.WorkspaceFailed += (sender, e) =>
            {
                Console.WriteLine($"Workspace error: {e.Diagnostic}");
            };

            Project project = await workspace.OpenProjectAsync(projectPathFileName);

            string rootNamespace = project.DefaultNamespace ?? "";

            List<string> viewModelClasses = new();

            foreach (Document document in project.Documents)
            {
                Console.WriteLine($"Analyzing file {document.Name}");

                SemanticModel? model = await document.GetSemanticModelAsync();

                if (model == null) continue;

                SyntaxNode? root = await document.GetSyntaxRootAsync();

                if (root == null) continue;

                IEnumerable<ClassDeclarationSyntax> classes = root.DescendantNodes().OfType<ClassDeclarationSyntax>();

                foreach (ClassDeclarationSyntax classDeclaration in classes)
                {
                    if (model.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
                    {
                        continue;
                    }

                    foreach (AttributeData attributeData in classSymbol.GetAttributes())
                    {
                        string? attributeName = attributeData.AttributeClass?.ToDisplayString();

                        if (attributeName == "CastelloBranco.LocatorGenerator.RegisterOnLocatorAttribute")
                        {
                            string className = classSymbol.ToDisplayString();
                            Console.WriteLine($"Found ViewModel {className}");
                            viewModelClasses.Add(className);
                        }
                    }
                }
            }

            string generatedSource = GenerateViewModelLocator(viewModelClasses, rootNamespace);

            Directory.CreateDirectory(outputDirectory);

            string fileName = Path.Combine(solutionPath, outputDirectory, "ViewModelLocator.g.cs");

            await File.WriteAllTextAsync(fileName, generatedSource);

            Console.WriteLine($"Code generation completed successfully - {fileName} was generated.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Code generation aborted unexpectedly - Exception: \r\n {ex}");
        }
    }

    private static string GenerateViewModelLocator(List<string> viewModelClasses, string rootNamespace)
    {
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file was automatically generated by the LocatorGenerator tool.");
        sb.AppendLine("// Changes to this file may cause incorrect behavior and will be lost");
        sb.AppendLine("// if the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using CommunityToolkit.Mvvm.DependencyInjection;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(rootNamespace))
        {
            sb.AppendLine($"namespace {rootNamespace};");
            sb.AppendLine();
        }

        if (string.IsNullOrEmpty(Version))
        {
            sb.AppendLine("[GeneratedCode(\"LocatorGenerator\")]");
        }
        else
        {
            sb.AppendLine($"[GeneratedCode(\"LocatorGenerator\", \"{Version}\")]");
        }

        sb.AppendLine("public partial class ViewModelLocator ");
        sb.AppendLine("{");

        sb.AppendLine("");
        sb.AppendLine("public ViewModelLocator () { }");
        sb.AppendLine("");

        foreach (string viewModel in viewModelClasses)
        {
            string fullQualifiedName = viewModel;
            string shortTypeName = viewModel.Split('.')[^1];

            sb.AppendLine($"    public static {fullQualifiedName}? {shortTypeName} => Ioc.Default.GetRequiredService<{fullQualifiedName}>();");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}
